name: scout_connect
description: A Flutter app for connecting athletes and scouts.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.5.0
  firebase_auth: ^5.3.3
  firebase_storage: ^12.3.6
  table_calendar: ^3.1.2
  provider: ^6.0.0
  http: ^1.2.2
  shared_preferences: ^2.0.8
  intl: ^0.19.0
  firebase_core: ^3.8.0
  image_picker: ^0.8.4+4
  google_sign_in: ^5.4.2
  logger: ^1.0.0
  video_player: ^2.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/images/google_logo.png
    - assets/images/default_profile.png

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
